# Generated by rust2rpm 10
%bcond_without check
%global debug_package %{nil}

%global crate actix

Name:           rust-%{crate}
Version:        0.8.3
Release:        4%{?dist}
Summary:        Actor framework for Rust

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/actix
Source:         %{crates_source}
# Initial patched metadata
# * Update derive_move to 0.15, hashbrown to 0.5, https://github.com/actix/actix/pull/265
# * Update parking_lot to 0.9, https://github.com/actix/actix/pull/273
Patch0:         actix-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Actor framework for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGES.md MIGRATION.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+actix-http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+actix-http-devel %{_description}

This package contains library source intended for building other packages
which use "actix-http" feature of "%{crate}" crate.

%files       -n %{name}+actix-http-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http-devel %{_description}

This package contains library source intended for building other packages
which use "http" feature of "%{crate}" crate.

%files       -n %{name}+http-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+mailbox_assert-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mailbox_assert-devel %{_description}

This package contains library source intended for building other packages
which use "mailbox_assert" feature of "%{crate}" crate.

%files       -n %{name}+mailbox_assert-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+resolver-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+resolver-devel %{_description}

This package contains library source intended for building other packages
which use "resolver" feature of "%{crate}" crate.

%files       -n %{name}+resolver-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+tokio-tcp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-tcp-devel %{_description}

This package contains library source intended for building other packages
which use "tokio-tcp" feature of "%{crate}" crate.

%files       -n %{name}+tokio-tcp-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+trust-dns-resolver-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-resolver-devel %{_description}

This package contains library source intended for building other packages
which use "trust-dns-resolver" feature of "%{crate}" crate.

%files       -n %{name}+trust-dns-resolver-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Aug 06 09:09:24 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.3-4
- Update parking_lot to 0.9

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.3-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Jun 18 10:10:14 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.3-2
- Update dependencies

* Thu May 30 18:30:27 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.3-1
- Initial package
